- id: checkstyle
  name: checkstyle
  description: "Runs the Checkstyle static code analysis tool."
  language: docker
  entry: /bin/bash /opt/run_checkstyle.sh
  files: \.java$
  require_serial: true
